import { setupServer } from 'msw/node';
import { getPetMock as getServerPetMock } from './gen/server/pet/pet.msw';

import ReactQueryProvider from './providers/reactQueryProvider';
import MockProvider from './providers/mockProvider';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const server = setupServer();
server.use(...getServerPetMock());
server.listen();

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactQueryProvider>
          <MockProvider/>
          {children}
        </ReactQueryProvider>
      </body>
    </html>
  );
}